/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IModuleInterface extends ethers.utils.Interface {
  functions: {
    "addModule(address,address)": FunctionFragment;
    "init(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addModule",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "init", values: [string]): string;

  decodeFunctionResult(functionFragment: "addModule", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "init", data: BytesLike): Result;

  events: {};
}

export class IModule extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IModuleInterface;

  functions: {
    addModule(
      _wallet: string,
      _module: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    init(_wallet: string, overrides?: Overrides): Promise<ContractTransaction>;
  };

  addModule(
    _wallet: string,
    _module: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  init(_wallet: string, overrides?: Overrides): Promise<ContractTransaction>;

  staticCall: {
    addModule(
      _wallet: string,
      _module: string,
      overrides?: Overrides
    ): Promise<void>;

    init(_wallet: string, overrides?: Overrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    addModule(_wallet: string, _module: string): Promise<BigNumber>;
    init(_wallet: string): Promise<BigNumber>;
  };

  populateTransaction: {
    addModule(_wallet: string, _module: string): Promise<PopulatedTransaction>;
    init(_wallet: string): Promise<PopulatedTransaction>;
  };
}
